# Generated by scripts/update-homebrew-tap.mjs on each release.
cask "lowtide" do
  arch arm: "arm64", intel: "x64"

  version "1.0.30"
  sha256 arm:   "4b42e358e8ab3aa077618ce36e3aae94432a6d75414f5bdc0f37e48d8dc257a1",
         intel: "01bef42f5c779718d919af94f83aba6e69cd8d906c884a8bbd59f3c05446178c"

  url "https://github.com/hrozno2/lowtide/releases/download/v#{version}/LowTide-#{version}-mac-#{arch}.dmg"
  name "Low Tide"
  desc "Writing app for novels and screenplays"
  homepage "https://github.com/hrozno2/lowtide"

  app "Low Tide.app"

  zap trash: [
    "~/Library/Application Support/Low Tide",
    "~/Library/Preferences/com.lowtide.writer.plist",
    "~/Library/Saved Application State/com.lowtide.writer.savedState",
  ]
end
