# Generated by scripts/update-homebrew-tap.mjs on each release.
cask "lowtide" do
  arch arm: "arm64", intel: "x64"

  version "1.0.33"
  sha256 arm:   "e0eeae989ca69942c00344a9bc7ce5693e5e8fda703e49edb1ee769b8260fbfa",
         intel: "3009b571c4be37e78012d56b3c31aebd4a2555d1ec4eeb3bd1124893e4d6dcbf"

  url "https://github.com/hrozno2/lowtide/releases/download/v#{version}/LowTide-#{version}-mac-#{arch}.dmg"
  name "Low Tide"
  desc "Writing app for novels and screenplays"
  homepage "https://github.com/hrozno2/lowtide"

  app "Low Tide.app"

  zap trash: [
    "~/Library/Application Support/Low Tide",
    "~/Library/Preferences/com.lowtide.writer.plist",
    "~/Library/Saved Application State/com.lowtide.writer.savedState",
  ]
end
