# Generated by scripts/update-homebrew-tap.mjs on each release.
cask "lowtide" do
  arch arm: "arm64", intel: "x64"

  version "1.0.31"
  sha256 arm:   "ca97bfd57e7594d7c2e73c4c59ff155b0724277766f192f8e529b03d0f8af8d2",
         intel: "94b9988938e107dac254241ab6ae9e11457e87d74a314e9727e952247bfcf44d"

  url "https://github.com/hrozno2/lowtide/releases/download/v#{version}/LowTide-#{version}-mac-#{arch}.dmg"
  name "Low Tide"
  desc "Writing app for novels and screenplays"
  homepage "https://github.com/hrozno2/lowtide"

  app "Low Tide.app"

  zap trash: [
    "~/Library/Application Support/Low Tide",
    "~/Library/Preferences/com.lowtide.writer.plist",
    "~/Library/Saved Application State/com.lowtide.writer.savedState",
  ]
end
